POST http://localhost:8080/tasks
Content-Type: application/json

{
  "title": "学习 MyBatis 的 Insert"
}

###

GET http://localhost:8080/tasks/3

###

PATCH http://localhost:8080/tasks/99/status
Content-Type: application/json

{
  "status": "IN_PROGRESS"
}

###

GET http://localhost:8080/tasks/999

###

POST http://localhost:8080/tasks
Content-Type: application/json

{
  "title": "用于测试删除的任务"
}

###

DELETE http://localhost:8080/tasks/5

###

GET http://localhost:8080/tasks/5